language: objective-c
osx_image: xcode8.3

# set up SonarCube
addons:
  sonarcloud:
    organization: "devex-aad"
    token:
      secure: "RXczf7TfFH5rveDaP5iAIet6waDOFO86uTsyM8lmUZrxwHgrwgDChimURPqCeqG9iCNuV+qDO/N7HgI1YJ+s9N2tK/zKOtd1LZFP9c6mVPHOZjY/Sy0DjhOu7XZUex0suqfQDfKJ0wkj+pcMrGfnFAyMtxtow6APk++1Oj1rOAw="
    branches:
     - master
     - dev

# Set up our rubygems (slather and xcpretty, namely)
install: 
 - gem install xcpretty -N
 
before_script:
# Tell the shell to echo failure codes up the pipe so that Travis will properly fail the
# build when the xcodebuild command fails
  - set -o pipefail

script:  
# Run the ADAL build script
  - ./build.py --no-clean
  - sonar-scanner

after_success:
# Run slather once to have it print out the results in the travis log
#  - slather coverage -s ADAL/ADAL.xcodeproj

notifications:
  slack:
    secure: BIziStN+8QJLjdqNbLyRWWw9kI/MQsX+rZq+xz/bfTANk0gbEryLgMSiEoHxdoctu0dOqOet1voYuDKs3RQW3W0yh0AhDwVgWThNkTA0oDXF8zqm9AXettXNtmYHipaYb6+z6L4lpJOkClQp3hAheu8cM2igqye1O0FQla9g/PA=

