language: objective-c
before_install:
  - sudo easy_install cpp-coveralls
script: 
  - xcodebuild -workspace ADALiOS.xcworkspace -scheme ADALiOS -configuration CodeCoverage -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xcodebuild test -workspace ADALiOS.xcworkspace -scheme ADALiOS -configuration CodeCoverage -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - find ~/Library/Developer/Xcode/DerivedData/ -not -path "*x86_64*" -not -path "*ADALiOSTests*" -name "*.gcno" -exec cp -v '{}' . \;
  - find ~/Library/Developer/Xcode/DerivedData/ -not -path "*x86_64*" -not -path "*ADALiOSTests*" -name "*.gcda" -exec cp -v '{}' . \;
  - xcodebuild -workspace ADALiOS.xcworkspace -scheme MyTestiOSApp -configuration CodeCoverage -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xcodebuild test -workspace ADALiOS.xcworkspace -scheme MyTestiOSApp -configuration CodeCoverage -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - find ~/Library/Developer/Xcode/DerivedData/ -not -path "*x86_64*" -not -path "*ADALiOSTests*" -not -path "*MyTestiOSApp*" -name "*.gcno" -exec cp -v '{}' . \;
  - find ~/Library/Developer/Xcode/DerivedData/ -not -path "*x86_64*" -not -path "*ADALiOSTests*" -not -path "*MyTestiOSApp*" -name "*.gcda" -exec cp -v '{}' . \;

after_success:


